version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
      - ./services/backend:/usr/src/app
    command: npm run start:dev
