name: Backend CI

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./services/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm ci
      - run: npm lint
